### ISSUE TITLE
View merge error on couchbase cloud

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/cbgb#3]
Currently on couchbase cloud, we're seeing an issue where none of the dashboards show up.

After digging into it, on the db1 machine I'm seeing this error in the logs:

```
Apr 11 11:17:53 db1 2014-04-11T18:  21:46Z ip-10-165-2-167 cbgb[18614]: View merge error:  could not convert jv, err: SyntaxError: Unexpected token ILLEGAL ("function(doc, oldDoc) {) (line 1)
```

Does that error seem severe enough to break the couchbase cloud UI?  Does it look like something that needs to be fixed in cbgb?

**Comment by ns-codereview** [comment]
Issue has been moved to http://cbugg.hq.couchbase.com/bug/bug-969
